#!/bin/sh

if [[ "$OSTYPE" == "darwin"* ]]; then

    if (test -e "/Applications/Emacs.app") ; then
        EMACS="/Applications/Emacs.app/Contents/MacOS/Emacs"

    elif (test -e "$HOME/Applications/Emacs.app") ; then
        EMACS="$HOME/Applications/Emacs.app/Contents/MacOS/Emacs"
    fi
fi

echo $EMACS
$EMACS -nw --batch -l org setup.org -f org-babel-tangle

echo Setting up...

./setup.sh
