#!/bin/sh

EMACS="Contents/MacOS/Emacs"

if (test -e "/Applications/Emacs.app") ; then
  /Applications/Emacs.app/$EMACS -nw --batch -l org setup.org -f org-babel-tangle
elif (test -e "$HOME/Applications/Emacs.app") ; then
  $HOME/Applications/Emacs.app/$EMACS -nw --batch -l org setup.org -f org-babel-tangle
else
  echo "Unable to locate Emacs"
fi

